[plugins]
kotlin-jvm = { id = "com.wsr.jvm", version = "unspecified" }
kotlin-multiplatform = { id = "com.wsr.multiplatform", version = "unspecified" }
maven-publish = { id = "com.wsr.maven.publish", version = "unspecified" }
